#fc	:= ifort
fc	:= gfortran

ifeq ($(FC), ifort)
	fflags	:= -O3 -convert big_endian -openmp
        #-CB -traceback -g #-check all -warn all -traceback
else
	fflags	:= -O3 -fopenmp -fconvert=big-endian
endif

src	:= $(wildcard *.f90)

prg	:= $(src:%.f90=%)

#########################################################################

all: $(prg)

%: %.f90
	$(fc) $(fflags) $< -o $@

clean:
	rm -f *~ $(prg) *.mod
